server:
  port: 8082
  servlet:
    context-path: /icefish
spring:
  datasource:
    url: jdbc:mysql://140.143.206.40:3306/nideshop?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: liyu
    password: 623763070Liyu;